-- Create pillar_flow table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.pillar_flow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Function/Cycle related
    stress_level INTEGER CHECK (stress_level BETWEEN 1 AND 10),
    sleep_hours NUMERIC(4, 1),
    relaxation_frequency INTEGER,
    exercise_type TEXT,
    morning_sunlight TEXT,
    endocrine_disruptors TEXT,
    bedtime_routine TEXT,
    emotional_state INTEGER CHECK (emotional_state BETWEEN 1 AND 10),
    
    -- Legacy/Compatibility fields
    sleep_hours_avg NUMERIC(4, 1),
    smoker TEXT,
    mental_load INTEGER,
    mental_rumination INTEGER,
    physical_anxiety BOOLEAN,
    alertness INTEGER,
    regulation_tools BOOLEAN,
    social_pressure INTEGER,
    emotional_support BOOLEAN,
    loneliness INTEGER,
    frequent_conflicts BOOLEAN,
    sleep_quality INTEGER,
    nocturnal_awakenings TEXT,
    nighttime_screen_use INTEGER,
    nap TEXT,
    morning_energy INTEGER,
    afternoon_energy INTEGER,
    coffee_cups INTEGER,
    libido INTEGER,
    emotional_connection_partner INTEGER,
    pain_dryness_relationships BOOLEAN,
    fertility_anxiety_relationships BOOLEAN,
    off_schedule_snacks TEXT,

    UNIQUE(user_id)
);

-- Enable RLS
ALTER TABLE public.pillar_flow ENABLE ROW LEVEL SECURITY;

-- Create policies securely (drop if exists procedure or DO block)
DO $$
BEGIN
    DROP POLICY IF EXISTS "Users can view their own flow pillar" ON public.pillar_flow;
    DROP POLICY IF EXISTS "Users can insert their own flow pillar" ON public.pillar_flow;
    DROP POLICY IF EXISTS "Users can update their own flow pillar" ON public.pillar_flow;
END
$$;

CREATE POLICY "Users can view their own flow pillar"
ON public.pillar_flow FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own flow pillar"
ON public.pillar_flow FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own flow pillar"
ON public.pillar_flow FOR UPDATE
USING (auth.uid() = user_id);

-- Grant permissions if needed (usually authenticated role has access by default in Supabase)
GRANT ALL ON public.pillar_flow TO authenticated;
GRANT ALL ON public.pillar_flow TO service_role;
