-- Migration: Create pillar_flora table and add new Flora form fields
-- Supports: digestive_symptoms, sibo_diagnosed, hpylori_diagnosed, skin_issues, hair_issues

-- Create pillar_flora table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.pillar_flora (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Campos existentes (mapeo desde formulario Flora)
    digestive_health INTEGER CHECK (digestive_health BETWEEN 0 AND 10),
    vaginal_health TEXT,
    antibiotics_last_year TEXT,
    fermented_foods_frequency INTEGER,
    food_intolerances TEXT,

    -- Nuevos campos Flora (síntomas, SIBO, H.Pylori, piel, cabello)
    digestive_symptoms TEXT,
    sibo_diagnosed BOOLEAN,
    hpylori_diagnosed BOOLEAN,
    skin_issues TEXT,
    hair_issues TEXT,

    -- Campos legacy/compatibilidad
    antibiotics_last_12_months TEXT,
    vaginal_infections BOOLEAN,
    altered_vaginal_ph BOOLEAN,
    previous_probiotics BOOLEAN,
    birth_lactation TEXT,
    bristol_stool_scale INTEGER,
    microbiome_tests TEXT,
    recommended_supplements TEXT,

    UNIQUE(user_id)
);

-- Add new columns if table already existed without them
ALTER TABLE public.pillar_flora ADD COLUMN IF NOT EXISTS digestive_symptoms TEXT;
ALTER TABLE public.pillar_flora ADD COLUMN IF NOT EXISTS sibo_diagnosed BOOLEAN;
ALTER TABLE public.pillar_flora ADD COLUMN IF NOT EXISTS hpylori_diagnosed BOOLEAN;
ALTER TABLE public.pillar_flora ADD COLUMN IF NOT EXISTS skin_issues TEXT;
ALTER TABLE public.pillar_flora ADD COLUMN IF NOT EXISTS hair_issues TEXT;

-- Enable RLS
ALTER TABLE public.pillar_flora ENABLE ROW LEVEL SECURITY;

-- Create policies (drop if exists to allow re-running)
DO $$
BEGIN
    DROP POLICY IF EXISTS "Users can view their own flora pillar" ON public.pillar_flora;
    DROP POLICY IF EXISTS "Users can insert their own flora pillar" ON public.pillar_flora;
    DROP POLICY IF EXISTS "Users can update their own flora pillar" ON public.pillar_flora;
END
$$;

CREATE POLICY "Users can view their own flora pillar"
ON public.pillar_flora FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own flora pillar"
ON public.pillar_flora FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own flora pillar"
ON public.pillar_flora FOR UPDATE
USING (auth.uid() = user_id);

-- Grant permissions
GRANT ALL ON public.pillar_flora TO authenticated;
GRANT ALL ON public.pillar_flora TO service_role;
