-- Create pillar_function table if it doesn't exist, or add missing columns
CREATE TABLE IF NOT EXISTS public.pillar_function (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    cycle_length INTEGER,
    regularity_detail TEXT,
    knows_fertile_days TEXT,
    luteal_phase_days INTEGER,
    fertile_mucus TEXT,
    pms_severity INTEGER,
    fertility_diagnosis TEXT,
    ovulation_tracking TEXT,
    menstrual_bleeding TEXT,
    diagnoses TEXT[],
    fertility_treatments TEXT,

    UNIQUE(user_id)
);

-- Add missing columns if table already existed with old schema
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS regularity_detail TEXT;
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS knows_fertile_days TEXT;
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS luteal_phase_days INTEGER;
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS fertile_mucus TEXT;
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS pms_severity INTEGER;
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS fertility_diagnosis TEXT;
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS ovulation_tracking TEXT;
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS menstrual_bleeding TEXT;
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS diagnoses TEXT[];
ALTER TABLE public.pillar_function ADD COLUMN IF NOT EXISTS fertility_treatments TEXT;

-- Enable RLS
ALTER TABLE public.pillar_function ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    DROP POLICY IF EXISTS "Users can view their own function pillar" ON public.pillar_function;
    DROP POLICY IF EXISTS "Users can insert their own function pillar" ON public.pillar_function;
    DROP POLICY IF EXISTS "Users can update their own function pillar" ON public.pillar_function;
END
$$;

CREATE POLICY "Users can view their own function pillar"
ON public.pillar_function FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own function pillar"
ON public.pillar_function FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own function pillar"
ON public.pillar_function FOR UPDATE
USING (auth.uid() = user_id);

GRANT ALL ON public.pillar_function TO authenticated;
GRANT ALL ON public.pillar_function TO service_role;
